### ISSUE TITLE
Does not work for C++

### ISSUE THREAD

**Issue by rizickus** [AlexCoderCorp/CDocComments#1]
Hello,
Extension does not work in C++ files when typing '/**' and pressing enter.
Typing '///' also does not have any effect in C/C++ files.

Installed extensions:
AlexCoderCorp.comments
DavidAnson.vscode-markdownlint
donjayamanne.githistory
DougFinke.vscode-pandoc
hars.CppSnippets
ms-vscode.cpptools
ms-vscode.PowerShell
robertohuertasm.vscode-icons
WakaTime.vscode-wakatime
yzane.markdown-pdf

Version 1.16.1.

**Comment by AlexCoderCorp** [comment]
Hello, thank you. I'm going to fix it.
